#!/bin/bash
current=$(swww query | head -1 | awk '{print $NF}' )
wallpaperpath=$HOME/Pictures/BingWallpaper/
echo $wallpaperpath
echo $current
python $HOME/.config/eww/scripts/bing-get.py

next=$(find "$wallpaperpath" -maxdepth 1 -type f -not -path '*/.*' -newer $current -printf '%T+\t%p\n' | sort -k 1 -M | head -1 | awk '{print $NF}')

if [[ -z "$next"  ]]; then
    next=$(find "$wallpaperpath" -maxdepth 1 -type f -not -path '*/.*' -printf '%T+\t%p\n' | sort -k 1 -M | head -1 | awk '{print $NF}')
fi
swww img $next --transition-type random --transition-pos "${cursorposx:-0}, ${cursorposy_inverted:-0}"
ln -sf $next $HOME/.config/eww/images/wallpaper
