return {
  eslint = require("lsp.eslint"),
  jdtls = require("lsp.jdtls"),
  jsonls = require("lsp.jsonls"),
  lua_ls = require("lsp.lua_ls"),
  volar = require("lsp.volar"),
  ts_ls = require("lsp.ts_ls"),
  yamlls = require("lsp.yamlls"),
  nixd = require("lsp.nixd"),
  pylsp = require("lsp.pylsp"),
  texlab = require("lsp.texlab"),
  bashls = {},
  cssls = {},
  html = {},
  lemminx = {},
  vale_ls = {},
  vimls = {},
  clangd = {},
  taplo = {},
  rust_analyzer = {},
  gopls = {},
}
